apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-backend
  template:
    metadata:
      labels:
        app: youtube-backend
    spec:
      containers:
      - name: youtube-backend
        image: nitishdevops/youtube:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URL
          value: "mongodb://mongo:27017/youtube"
